### ISSUE TITLE
base.defined cannot be overwritten.

### ISSUE THREAD

**Issue by onedayitwillmake** [d3fc/d3fc-series#57]
It does not appear to be possible to have a custom `defined` method for a series.
When attempting to pass one using the standard getter convention, the provided function is never invoked.

As an aside, it is the only one of the following methods below which cannot be chained as it does  not return the line-series itself, but instead returns the result of calling `src/defined.js`

```javascript
const lineSeries = fc.seriesSvgLine()
      .crossValue(d => d.date)
      .mainValue(d => d[this.name])
      .decorate((sel) =>{
        sel.enter().classed('rsi-line', true)
      });
lineSeries.defined((d,i,arr) => {
     console.log('never called');
     return Math.random() < 0.5)
})
```

**Comment by ColinEberhardt** [comment]
Good point - we'll look to fix that shortly

**Comment by msuperina** [comment]
I am picking up this one.
