### ISSUE TITLE
Indenting between the candles

### ISSUE THREAD

**Issue by dormadekhin-denis** [d3fc/d3fc-series#58]
How can I add indents between candles for seriesSvgCandlestick?

**Comment by ColinEberhardt** [comment]
What do you mean by indents? Can you provide a picture that illustrates?

**Comment by dormadekhin-denis** [comment]
![image](https://user-images.githubusercontent.com/32381310/41766620-b40121a6-7631-11e8-8b32-a475353fe421.png)

**Comment by ColinEberhardt** [comment]
This issue was moved to d3fc/d3fc#1121
