### ISSUE TITLE
Broken containerTranslation() in 3.2.0

### ISSUE THREAD

**Issue by kasparsd** [d3fc/d3fc-series#60]
Introduced in 3.2.0, possibly 0f849b2d.

Looking at `examples/candlestick.html` we see that `containerTranslation(base.values(d, i))` in

https://github.com/d3fc/d3fc-series/blob/2a02aa657b83c68e96ad73b97916417dde3457c2/src/svg/boxPlot.js#L40

now returns `translate(function base() {}0, function base() {})` which produces invalid HTML.

The same call in 3.1.1 returns `translate(38.46153846153847, 205.18025940353056)`.

**Comment by ColinEberhardt** [comment]
Thanks for the bug report - we'll take a look. @msuperina can you please investigate?

**Comment by kasparsd** [comment]
I think it's because `base.xScale(crossValue(d, i))` now always returns `function base() {}` due to the refactoring in 0f849b2d8f855386b972e30e6d22842c245dad33.

**Comment by msuperina** [comment]
@kasparsd thanks for taking the time to look into it. I now see what is happening, `xScale` used to be a separate variable in the scope created by the default export in `boxPlotBase`, and passing a first argument to `base.xScale` was overriding the enclosed `xScale`. Now it is overriding `base.xScale` directly. Let me check with @ColinEberhardt
